//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsToOrganization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string RandomName { get; set; }
        public string Course { get; set; }
        public long Gr { get; set; }
        public long Sec { get; set; }
        public string GithubLogin { get; set; }
        public string CreateDate { get; set; }
    }
}
